# export GOPRIVATE=github.com/adoublef/priv && go get github.com/adoublef/priv@latest
# https://www.arhea.net/posts/2023-09-12-building-distroless-go-containers/
# https://www.jvt.me/posts/2025/01/14/go-private-docker/
# https://github.com/docker/build-push-action
#
# https://www.jvt.me/posts/2025/01/14/go-private-docker/
# https://www.arhea.net/posts/2023-09-12-building-distroless-go-containers/
# https://github.com/docker/build-push-action/issues/714
# ssh-keygen -t ed25519 -C "github-actions" -f ~/.ssh/github_actions -N ""
# https://github.com/aquasecurity/trivy-action#using-trivy-with-github-code-scanning
name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      contents: read # Required to checkout and read repo files
      security-events: write # Required to upload SARIF files to Security tab

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.10.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          context: .
          ssh: default
          push: false
          tags: docker.io/adoublef/calc:${{ github.sha }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: docker.io/adoublef/calc:${{ github.sha }}
          format: "sarif"
          output: "trivy-results.sarif"

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: "trivy-results.sarif"
